Exception in thread Thread-1 (train):
Traceback (most recent call last):
  File [35m"/Users/matt/.local/share/uv/python/cpython-3.13.0-macos-aarch64-none/lib/python3.13/threading.py"[0m, line [35m1041[0m, in [35m_bootstrap_inner[0m
    [31mself.run[0m[1;31m()[0m
    [31m~~~~~~~~[0m[1;31m^^[0m
  File [35m"/Users/matt/.local/share/uv/python/cpython-3.13.0-macos-aarch64-none/lib/python3.13/threading.py"[0m, line [35m992[0m, in [35mrun[0m
    [31mself._target[0m[1;31m(*self._args, **self._kwargs)[0m
    [31m~~~~~~~~~~~~[0m[1;31m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m
  File [35m"/Users/matt/Developer/embedded/inverted_pendulum/python/src/train.py"[0m, line [35m152[0m, in [35mtrain[0m
    artifact = wandb.Artifact("models/best-model", type="model")
  File [35m"/Users/matt/Developer/embedded/inverted_pendulum/python/.venv/lib/python3.13/site-packages/wandb/sdk/artifacts/artifact.py"[0m, line [35m140[0m, in [35m__init__[0m
    raise ValueError(
    ...<2 lines>...
    )
[1;35mValueError[0m: [35mArtifact name may only contain alphanumeric characters, dashes, underscores, and dots. Invalid name: models/best-model[0m
Traceback (most recent call last):
  File "/Users/matt/Developer/embedded/inverted_pendulum/python/src/train.py", line 220, in <module>
    main()
    ~~~~^^
  File "/Users/matt/Developer/embedded/inverted_pendulum/python/src/train.py", line 202, in main
    visualizer.run()
    ~~~~~~~~~~~~~~^^
  File "/Users/matt/Developer/embedded/inverted_pendulum/python/src/gui.py", line 430, in run
    dpg.render_dearpygui_frame()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/matt/Developer/embedded/inverted_pendulum/python/.venv/lib/python3.13/site-packages/dearpygui/dearpygui.py", line 9264, in render_dearpygui_frame
    return internal_dpg.render_dearpygui_frame(**kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyboardInterrupt
